### ISSUE TITLE
Rudimentary MPE support

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/dexed#1]
There's a lot to MPE support but lets start with some basics

- PitchBendRange is in the params window and persisted
- PitchBend per channel works with voices

so you only get the on / off / velocity / bend and not the per-channel aftertouch or release velocity or timbre at first, but can we even get this far?

**Comment by mkruselj** [comment]
Gotta increase pitch bend range to 48 semitones max, too!

**Comment by baconpaul** [comment]
Most synths including surge store a distinct mpe pitchbend from wheel pitch bend and I planned same here. But yup!

**Comment by mkruselj** [comment]
Suggested implementation:

- use existing method of how controllers are assigned to various targets (modwheel, breath, foot pedal, aftertouch -> pitch LFO amount, amp LFO amount, operator volumes/EG bias)
- when MPE mode is enabled, aftertouch assignment would be per channel
- add a new target, which would be Brightness (relatively adjusts output levels of all modulators in the algorithm
- add Timbre (CC 74) as another controller to choose from
- add global/per patch switch for the whole controller section, so that we could store all this stuff per patch easily

- when UI is redesigned, move out the controllers section to front panel rather than a separate modal dialog

**Comment by baconpaul** [comment]
Yeah I agree with that and have been coding thinking I would do that but I’m going to bounce it to another ticket and close this one when we have pitch bend and a control panel working only so I can merge (although all my data structure capture the full state they just don’t do anything with timbre pressure and release)

**Comment by baconpaul** [comment]
OK the release we just did supports MPE for pitch. Open the "PARAM" window and click MPE on and pick your pitch bend range and go for it.

Closing this issue since I moved the next step of things over to a more design-focused advanced MPE issue.
